; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _brickStreetObjects

._brickStreetObjects
defb @00001001, @00010000, @00001000, @00010001
defb @00000001, @00000101, @00000010, @00000001
defb @00000101, @00010101
