; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _buckHouseObjects

._buckHouseObjects
defb @00001001, @00000010, @00000011, @00000101
defb @00010100, @00000000, @00000000, @00011100
defb @00010001, @00001100
