; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _castleObjects

._castleObjects
defb @00000110, @00000110, @00000100, @00000011
defb @00010000, @00001001, @00000001
