; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _castleCornerObjects

._castleCornerObjects
defb @00010101, @00010000, @00000111, @00010001
defb @00000110, @00000100, @00010101, @00001110
defb @00000110, @00000001, @00000100, @00001110
defb @00000000, @00000100, @00001110, @00001000
defb @00000101, @00001110, @00010100, @00000101
defb @00001110, @00010001
