; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _cornerShopObjects

._cornerShopObjects
defb @00001111, @00001010, @00000101, @00000001
defb @00010010, @00000100, @00010101, @00001111
defb @00000110, @00000000, @00010000, @00001001
defb @00010011, @00010000, @00001001, @00001000
