; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _deadEndStreetObjects

._deadEndStreetObjects
defb @00000110, @00001100, @00000110, @00000001
defb @00001101, @00000110, @00010010
