; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _factoryObjects

._factoryObjects
defb @00001001, @00000111, @00000101, @00000000
defb @00000111, @00000101, @00010011, @00001111
defb @00000100, @00010010
