; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _poshStreetObjects

._poshStreetObjects
defb @00001111, @00001010, @00000100, @00000001
defb @00001010, @00000100, @00010100, @00000100
defb @00001101, @00011101, @00000100, @00001101
defb @00001001, @00000101, @00001011, @00010001
