; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _ruralStreet2Objects

._ruralStreet2Objects
defb @00001100, @00001110, @00000101, @00010110
defb @00010001, @00000110, @00000000, @00011001
defb @00001100, @00010001, @00000100, @00001101
defb @00001001
