; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _ruralStreetObjects

._ruralStreetObjects
defb @00001001, @00001110, @00000110, @00000001
defb @00001110, @00000110, @00010101, @00000011
defb @00001011, @00010010
