; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _townSquareObjects

._townSquareObjects
defb @00001111, @00010001, @00000110, @00000000
defb @00010101, @00000101, @00010101, @00010110
defb @00001010, @00010011, @00010111, @00001011
defb @00000101, @00011000, @00001100, @00001001
