; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _victorianStreetObjects

._victorianStreetObjects
defb @00001001, @00010001, @00000110, @00000000
defb @00001001, @00001101, @00010001, @00010001
defb @00000110, @00010100
