; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _bush1Tilemap

._bush1Tilemap
defb @00000110, @00000011, @00000000, @01000110
defb @00000000, @01000111, @01001000, @01000111
defb @01001101, @01001000, @01001001, @01000111
defb @01001001, @01001110, @01001101, @01001110
defb @01001001, @01011101, @01001001, @01011110
