; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _bush2Tilemap

._bush2Tilemap
defb @00000100, @00000100, @00000000, @00000000
defb @01000110, @00000000, @01001101, @01001110
defb @01001110, @01000101, @01001111, @01001110
defb @01001001, @01001111, @01001011, @01001001
defb @01001001, @01001100
