; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _bush3Tilemap

._bush3Tilemap
defb @00000100, @00000011, @00000000, @01000110
defb @01000110, @01000011, @01000111, @01001001
defb @01001001, @01001001, @01001001, @00101110
defb @01001001, @00101010
