; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _pavementTilemap

._pavementTilemap
defb @00000010, @00000110, @00100001, @00100001
defb @00100001, @00100001, @00100001, @00100001
defb @00111000, @00111000, @00111000, @00111000
defb @00111000, @00111000
