; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _pubSign2Tilemap

._pubSign2Tilemap
defb @00000010, @00000010, @00001111, @10101110
defb @01111000, @00001111
