; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _pubSign1Tilemap

._pubSign1Tilemap
defb @00000010, @00000010, @10111010, @10111011
defb @10111100, @10111101
