; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user

PUBLIC _streetlampTilemap

._streetlampTilemap
defb @00001100, @00000001, @01011100, @01011011
defb @01011010, @01011001, @01011001, @01011001
defb @01011001, @01011001, @01011000, @01010111
defb @01010111, @01010110
