; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user
public _ghostSmallSprite

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000

._ghostSmallSprite
defb @00111100
defb @01011010
defb @01001010
defb @11111111
defb @11100111
defb @11000011
defb @11101011
defb @01010101

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
