; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user
public _moonSmallSprite

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000

._moonSmallSprite
defb @00111100
defb @01001110
defb @10011011
defb @10101001
defb @01011110
defb @10101011
defb @01101110
defb @00111100

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
