; file generated by Spectrum Asset Maker
; https://github.com/clebin/SpectrumAssetMaker

section rodata_user
public _saucerSmallSprite

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000

._saucerSmallSprite
defb @00011000
defb @00100100
defb @01010010
defb @01000010
defb @01111110
defb @10000001
defb @10101011
defb @01111110

defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
defb @00000000
